
spring:
  jmx:
      enabled: false
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/quantification
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mail:
    host: smtp.office365.com
    port: 587
    protocol: smtp
    username: hytest01@huobi.com
    password: HB0523hb17940
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 25000

mybatis:
  mapperLocations: classpath:mapper/*.xml
  config: classpath:mybatis/mybatis-config.xml

zookeeper:
  address: 127.0.0.1:2181
