
spring:
  redis:
    host: 172.18.6.200
    port: 6379
    password: root
  datasource:
    name: test
    url: jdbc:mysql://172.18.6.200:3306/quantification
    username: root
    password: root

zookeeper:
  address: 172.18.6.200:2181

