server:
  port: 8082


spring:
  jmx:
      enabled: false
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/quantification
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl


mybatis:
  mapperLocations: classpath:mapper/*.xml
  config: classpath:mybatis/mybatis-config.xml


