server:
  port: 8081


spring:
  jmx:
      enabled: false
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/quantification
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapperLocations: classpath:mapper/*.xml
  config: classpath:mybatis/mybatis-config.xml

zookeeper:
  address: 127.0.0.1:2181


strategy:
  group1:
    enable: false
    future:
      exchangeId: 0
      accountId: 101
      baseCoin: btc
      quotCoin: usd
      contractCode: BTC180803
      lever: 10
    spot:
      exchangeId: 1
      accountId: 101
      baseCoin: btc
      quotCoin: usdt
  group2:
    enable: true
    future:
      exchangeId: 0
      accountId: 101
      baseCoin: btc
      quotCoin: usd
      contractCode: BTC180810
      lever: 10
    spot:
      exchangeId: 1
      accountId: 101
      baseCoin: btc
      quotCoin: usdt
  group3:
    enable: false
    future:
      exchangeId: 0
      accountId: 101
      baseCoin: btc
      quotCoin: usd
      contractCode: BTC180928
      lever: 10
    spot:
      exchangeId: 1
      accountId: 101
      baseCoin: btc
      quotCoin: usdt